### PR TITLE
Issue #137: Added help text to chaos run (yaml, json)

### PR DESCRIPTION
**Pull request by nstjelja**

### CODE REVIEW

**Comment by Lawouach** [comment]
Looks good to me but could you sign your commit and force push please? :) The DCO will likely keep complaining but don't worry about it :)

**Comment by nstjelja** [comment]
Done :)

**Comment by Lawouach** [comment]
Tx!

**Comment by Lawouach** [comment]
Bizarrely, I don't see the "SignOff" in the [commit](https://github.com/nstjelja/chaostoolkit/commit/e8e652791e320ea5e45fde660db31bf827cd7199). Sorry to be a pain :( Just trying to be clean and figure out what's going on.

**Pull request merged**
