### PR TITLE
Correct mispelling in hypotesis tags.

### PR DESCRIPTION
**Pull request by CamilleGR**
Correct the mispelling of issues #211.

All tests pass but I don't know what are the consequences on this correction on the chaostoolkit's plugins. 

It's my first open source PR, let me know if I have to do something differently.

### CODE REVIEW

**Review by russmiles — APPROVED** [review]
Looks good to me. Thanks for your first open source PR!

**Review by Lawouach — CHANGES_REQUESTED** [review]
This is a breaking change the way it's offered in this PR.

Maybe we should have a couple of versions where:

* we support both ways of writing the word
* when we detect the wrong one, we issue a warning message that this is now deprecated and will be dropped in a future release
* pass on the correct value to the lib so that we can change the lib but not break anything for now.

**Comment by Lawouach** [comment]
I need time to go through this PR a bit so I'm pausing it for now.

**Comment by laixintao** [comment]
This PR is good, is there any chance for this to get merged?

**Review by laixintao — APPROVED** [review]

**Comment by CharlieMoon37** [comment]
I have created and merged a similar PR that solves this issue: #235

**Pull request closed without merging**
