### PR TITLE
Updated Release Workflow

### PR DESCRIPTION
**Pull request by CharlieMoon37**
Added a section similar to that of the `check_pr.yaml` in `release.yaml` to ensure both the `CHANGELOG.md` and `chaostoolkit/__init__.py` files are changed in an attempt to ensure releases are carried out correctly and that the version is correctly updated

Signed-off-by: Charlie Moon <charlie@chaosiq.io>

### CODE REVIEW

**Comment by ciaranevans** [comment]
@CharlieMoon37 this all seems OK to me, I have one main question though - How does it know what files are modified? I'm not sure this will pickup changed files as the workflow run isn't a PR so there's technically no diff between it and the HEAD of the repo

It may well be smart enough though

**Comment by CharlieMoon37** [comment]
> @CharlieMoon37 this all seems OK to me, I have one main question though - How does it know what files are modified? I'm not sure this will pickup changed files as the workflow run isn't a PR so there's technically no diff between it and the HEAD of the repo
> 
> It may well be smart enough though

Nope, you are quite right. I was testing this on pushes to the master branch on a test repo instead of simulating a release each time. That's what you get for being lazy

**Comment by ciaranevans** [comment]
You might be able to specify that it checks the current commit, but I'm not sure how good that would work

**Comment by CharlieMoon37** [comment]
Yep, I'm having a look now

**Review by ciaranevans — APPROVED** [review]

**Pull request merged**
